### ISSUE TITLE
Add margin between list and header in navigation drawer

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/QCVOC#140]
![image](https://user-images.githubusercontent.com/17145758/45487684-bd73f900-b724-11e8-8cd7-2a6c509f9d84.png)

It looks funny the way it is.  10px ought to do it.

**Comment by brianhankins** [comment]
So you want a 10px bottom margin here?

![untitled](https://user-images.githubusercontent.com/15353420/45553987-f1b9e900-b7fa-11e8-9292-896d593c3dc9.png)
