### ISSUE TITLE
Rename credentialStore.js to credentials.js

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/QCVOC#197]
The simplified name is more consistent with similar files.

**Comment by bkgramling** [comment]
updated

**Comment by jpdillingham** [comment]
Thanks for this update.  We'll want to use the plural `credentials.js` instead of '

**Comment by bkgramling** [comment]
Okay, I updated the file and also ran the app and fixed a few locations that needed to have the updated name changed.

**Comment by wburklund** [comment]
Closed via #121
