### ISSUE TITLE
Allow scanner to be reset without refreshing

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/QCVOC#209]
Presently the user must select the Event and Service prior to using the scanner.  Once these are selected the app must be refreshed to change the selection.  Add a menu (https://material-ui.com/demos/menus/) to the top right corner of the scanner card and include an option to reset the scanner options.

**Comment by brianhankins** [comment]
Decided to work on this as removing the timer on the scan requires a reload each time.

**Comment by jpdillingham** [comment]
Probably want to create a separate issue for that; this is for scanner setup (e.g. allowing the user to re-select Event and Service)

**Comment by brianhankins** [comment]
> Add a menu (https://material-ui.com/demos/menus/) to the top right corner of the scanner card and include an option to reset the scanner options.

What do you mean by this then? Reset which options?

**Comment by jpdillingham** [comment]
Service and Event specifically
