### ISSUE TITLE
Remove the SetTimeOut after scan and add a refresh from the menu option

### ISSUE THREAD

**Issue by brianhankins** [qccoders/QCVOC#222]
This relates to #209 

1. Remove the timer after the scan and give the user an option to resetting the scanner card. 
2. Call this reset function right before each scan.

**Comment by jpdillingham** [comment]
I'm adding a menu to the Scanner interface to allow for things like resets, viewing history, etc:

![image](https://user-images.githubusercontent.com/17145758/46414362-920f7900-c6e8-11e8-9205-6bb64ad04b26.png)

I think it would be good to add 'Clear Previous Scan' to the menu to handle this, however we'll need to think of a way to disambiguate it from 'Reset Scanner', which allows users to re-select an Event/Service.  I guess they'll figure it out when they do it a few times and it isn't that disruptive.

**Comment by brianhankins** [comment]
> I'm adding a menu to the Scanner interface to allow for things like resets, viewing history, etc:
> 
> ![image](https://user-images.githubusercontent.com/17145758/46414362-920f7900-c6e8-11e8-9205-6bb64ad04b26.png)
> 
> I think it would be good to add 'Clear Previous Scan' to the menu to handle this, however we'll need to think of a way to disambiguate it from 'Reset Scanner', which allows users to re-select an Event/Service. I guess they'll figure it out when they do it a few times and it isn't that disruptive.

Will this menu also be on the scanner? I wasn't sure if this issue needs to also import this or if this issue will take the parent component and this issue would just add the option to 'Clear Previous Scan'.
