### ISSUE TITLE
Investigate whether it is possible to use a service more than once per event

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/QCVOC#313]
During discussion at the last site visit it was suggested that it may be possible for a veteran to pass through a service more than once by abusing the check in functionality.  Review the code and do some testing to determine whether this is possible, and if so, prevent it.

**Comment by wburklund** [comment]
https://github.com/qccoders/QCVOC/blob/97d3e53451e1d23010f815892540917a0788e7df/api/QCVOC.Api/Scans/Controller/ScansController.cs#L128-L163 It is not possible for a veteran to use a service more than once in a given event. `PUT /api/v1/scans` checks for any scans that share the same event, veteran, and service IDs. If a matching scan is found, it responds with 200 (duplicate scan). A change in PlusOne does not affect this.
