### ISSUE TITLE
Event Creation Time is Backwards

### ISSUE THREAD

**Issue by qcc-na** [qccoders/QCVOC#352]
When creating an event, the date fields don't display the time correctly.

Repro:
- Menu -> Events -> New Event
- Click "Start Date" (Also happens for "End Date")

Control says Month, Day, Minute, Hour
Should say: Month, Day, Hour, Minute

**Comment by jpdillingham** [comment]
https://github.com/dmtrKovalenko/material-ui-pickers/issues/780

Update `material-ui-pickers` package to ^2.0.4 to resolve.

**Comment by jpdillingham** [comment]
Fixed.
