### ISSUE TITLE
Update .NET copyright text

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/QCVOC#43]
```c#
    Copyright (c) QC Coders. All rights reserved. Licensed under the GPLv3 license. See LICENSE file
    in the project root for full license information.
```

Update the copyright template and all files to match the text above.  The template can be found in `stylecop.json`

**Comment by brianhankins** [comment]
@jpdillingham What are we doing with the copyright stuff? Are we going to keep adding our names to the list? I noticed Will added his name in code comments which is different from the example above. 

I also was looking for the stylecop.json file and I couldn't find it.
