### ISSUE TITLE
Non-persistent logins not handled properly

### ISSUE THREAD

**Issue by wburklund** [qccoders/QCVOC#59]
If a user logs in with the "Remember Me" box unchecked, they can't complete any actions requiring privileges. Also, they are returned to the login form on reload.

**Comment by wburklund** [comment]
This might be solved by storing credentials in Session Storage on logins where the "Remember Me" box is unchecked.

**Comment by jpdillingham** [comment]
I like the session storage idea.  Take a look at `credentialStore` and think about how the existing methods could be modified to support both local and session storage.

Ideally `getCredentials` would return whichever is used and `deleteCredentials` would delete from both.
